"""
Diverse unit test cases for the next-character predictor.
Each entry is (input_prefix, expected_next_character).
Designed to cover many unique scenarios; model is English-only so non-English and
symbol/code/edge cases should often fail, yielding ~10% or lower accuracy.
"""

# Format: list of (input_string, expected_next_char)
# Categories are commented for clarity; many unique ideas per category.

UNIT_TEST_CASES = [
    # ---- Non-English: Spanish ----
    ("Hola mund", "o"),
    ("¿Qué tal ", "e"),
    ("Buenos dí", "a"),
    ("Gracias por tu ayu", "d"),
    ("El gato está en la ventan", "a"),
    ("Me gusta la comid", "a"),
    ("Hasta luego, amig", "o"),
    ("¿Dónde está la bibliotec", "a"),
    ("No entiendo nad", "a"),
    ("Por favor, ayud", "a"),
    # ---- Non-English: French ----
    ("Bonjour le mond", "e"),
    ("Merci beaucou", "p"),
    ("Je ne sais pa", "s"),
    ("Comment allez-vous aujourd'hui", "'"),
    ("C'est la vi", "e"),
    ("Au revoir et à bientô", "t"),
    ("Je m'appelle Pierr", "e"),
    ("Où est la gare s'il vous plaî", "t"),
    ("Le chat noir est sur la tab", "l"),
    ("Très bien, merc", "i"),
    # ---- Non-English: German ----
    ("Guten Tag, wie geht e", "s"),
    ("Danke schö", "n"),
    ("Auf Wiedersehe", "n"),
    ("Ich heiße Han", "s"),
    ("Das ist wunderba", "r"),
    ("Wo ist die Toilette bit", "t"),
    ("Ein Buch über die Geschich", "t"),
    ("Gute Nacht und schlaf gu", "t"),
    ("Bitte sehr, gern geschehe", "n"),
    ("Der Hund läuft in den Gar", "t"),
    # ---- Non-English: Russian (Cyrillic) ----
    ("Привет ми", "р"),
    ("Спасибо больш", "о"),
    ("Как дела", "?"),
    ("Доброе утро", ","),
    ("До свидани", "я"),
    ("Меня зовут Алекса", "н"),
    ("Где здесь туалет", "?"),
    ("Это очень красив", "о"),
    ("Хорошего дн", "я"),
    ("Пожалуйста, помогите м", "н"),
    # ---- Non-English: Chinese ----
    ("你好世", "界"),
    ("谢谢你的帮", "助"),
    ("今天天气很好", "。"),
    ("我是学", "生"),
    ("再见，朋", "友"),
    ("请问厕所在哪", "里"),
    ("这个很好吃", "。"),
    ("明天见", "。"),
    ("对不起，我不懂", "。"),
    ("欢迎来到北", "京"),
    # ---- Non-English: Japanese ----
    ("こんにちは、元気", "で"),
    ("ありがとうございま", "す"),
    ("さようなら", "。"),
    ("私は学生で", "す"),
    ("今日はいい天気", "で"),
    ("トイレはどこですか", "？"),
    ("おいしいです", "ね"),
    ("明日また会いましょう", "。"),
    ("すみません、分かりません", "。"),
    ("日本へようこそ", "。"),
    # ---- Non-English: Arabic ----
    ("مرحبا بك", " "),
    ("شكرا جزيلا", " "),
    ("كيف حالك", "؟"),
    ("مع السلامة", " "),
    ("أنا طالب", " "),
    ("أين الحمام", "؟"),
    ("هذا لذيذ", " "),
    ("إلى اللقاء", " "),
    ("من فضلك ساعدني", " "),
    ("أهلا وسهلا", " "),
    # ---- Non-English: Portuguese ----
    ("Olá mundo", "!"),
    ("Obrigado pela ajud", "a"),
    ("Bom dia, como vai", "?"),
    ("Até logo, amig", "o"),
    ("Onde fica o banheir", "o"),
    ("Isso é delicios", "o"),
    ("Por favor, me ajud", "e"),
    ("Boa noite e durma be", "m"),
    ("Tudo bem com voc", "ê"),
    ("Bem-vindo ao Brasi", "l"),
    # ---- Non-English: Italian ----
    ("Ciao mondo", "!"),
    ("Grazie mille", "!"),
    ("Come stai ogg", "i"),
    ("A presto, amic", "o"),
    ("Dove si trova il bagn", "o"),
    ("È molto buon", "o"),
    ("Per favore, aiutatemi", "."),
    ("Buona notte e sogni d'or", "o"),
    ("Mi chiamo Luc", "a"),
    ("Benvenuto in Itali", "a"),
    # ---- Numbers and symbols ----
    ("42 ", " "),
    ("3.14159", "2"),
    ("100% ", "o"),
    ("$50.00 ", " "),
    ("2 + 2 ", "="),
    ("#hashtag ", " "),
    ("user@domain.", "c"),
    ("(555) 123-456", "7"),
    ("Version 2.0.", "0"),
    ("<html>", " "),
    # ---- Code and tech ----
    ("def ", " "),
    ("import ", "o"),
    ("function ", "("),
    ("return ", " "),
    ("https://www.goo", "g"),
    ("/usr/local/bi", "n"),
    ("git checkout ", "-"),
    ("npm install ", "-"),
    ("SELECT * FROM ", "t"),
    ("console.log(", "'"),
    # ---- Punctuation and formatting ----
    ("Mr. ", "S"),
    ("Dr. ", " "),
    ("e.g. ", " "),
    ("i.e. ", " "),
    ("U.S. ", " "),
    ("Yes! ", " "),
    ("Wait... ", " "),
    ("Note: ", " "),
    ("Hello—world", " "),
    ("(parenthesis) ", " "),
    # ---- Contractions and apostrophes ----
    ("don't ", "w"),
    ("it's ", "a"),
    ("I'm ", "s"),
    ("we're ", "g"),
    ("they've ", "b"),
    ("can't ", " "),
    ("won't ", " "),
    ("John's ", "c"),
    ("that's ", "w"),
    ("what's ", "u"),
    # ---- Rare or long English words ----
    ("xylophon", "e"),
    ("pneumoni", "a"),
    ("rhythm", " "),
    ("syzygy", " "),
    ("antidisestablishmentarianism", " "),
    ("supercalifragilisticexpialidociou", "s"),
    ("unbelievable", " "),
    ("questionnaire", " "),
    ("necessary", " "),
    ("accommodation", " "),
    # ---- Short / edge context ----
    ("", " "),
    ("a", " "),
    ("x", " "),
    ("q", "u"),
    ("z", " "),
    (" ", " "),
    ("\t", " "),
    (".", " "),
    ("?", " "),
    ("!", " "),
    # ---- Repetition and patterns ----
    ("aaaaaaa", "a"),
    ("aaaaaaa", " "),
    ("the the the ", "t"),
    ("abcabcab", "c"),
    ("1231231", "2"),
    # ---- Mixed language ----
    ("Hello 世界", " "),
    ("The café is ", "o"),
    ("naïve approach", " "),
    ("Pokémon and anime", " "),
    ("Café résumé", " "),
    ("Tokyo 東京", " "),
    ("Hola, I said ", "h"),
    ("C'est la vie baby", " "),
    ("Danke thank you", " "),
    ("Adiós friends", " "),
    # ---- Slang and informal ----
    ("OMG that's ", "s"),
    ("LOL so funn", "y"),
    ("BRB in a sec", " "),
    ("IMO the best", " "),
    ("FYI we're late", " "),
    ("TBH I don't know", " "),
    ("IDK what to do", " "),
    ("ASAP please", " "),
    ("RSVP by Friday", " "),
    ("DIY project", " "),
    # ---- Dates and time ----
    ("Jan 1, 202", "4"),
    ("12:30 ", "p"),
    ("Q1 202", "4"),
    ("March 15, 200", "0"),
    ("Mon Dec 0", "1"),
    ("09:00 AM", " "),
    ("1st place", " "),
    ("2nd floor", " "),
    ("3rd time", " "),
    ("Chapter IV", " "),
    # ---- Scientific / math ----
    ("π ≈ 3.14", "1"),
    ("α and β are", " "),
    ("Δx = ", "x"),
    ("E = mc²", " "),
    ("H₂O", " "),
    ("x → ∞", " "),
    ("∑ i = ", "1"),
    ("√2 ≈ ", "1"),
    ("∂f/∂x", " "),
    ("∫₀¹ x dx", " "),
    # ---- Quotes and brackets ----
    ("'Hello' ", "s"),
    ('"Yes" ', "s"),
    ("(example)", " "),
    ("[array]", " "),
    ("{key}: ", '"'),
    ("<tag>", " "),
    ("'Single quoted", "'"),
    ("\"Double quoted", '"'),
    ("Back `tick`", " "),
    ("—em dash—", " "),
    # ---- Emoji and Unicode ----
    ("Hello 😀", " "),
    ("Thumbs up 👍", " "),
    ("Café", " "),
    ("Zürich", " "),
    ("naïve", " "),
    ("résumé", " "),
    ("日本語", " "),
    ("한글", " "),
    ("مرحبا", " "),
    ("Привет", " "),
    # ---- Sentence boundaries ----
    ("Hello. ", "I"),
    ("Really? ", " "),
    ("No! ", " "),
    ("Okay. ", "L"),
    ("Done. ", " "),
    ("Sure. ", " "),
    ("Maybe. ", " "),
    ("Thanks. ", " "),
    ("Sorry. ", " "),
    ("Wait. ", " "),
    # ---- Common suffixes ----
    ("running ", " "),
    ("happily ", " "),
    ("question", " "),
    ("happiness", " "),
    ("beautiful", " "),
    ("quickly", " "),
    ("national", " "),
    ("important", " "),
    ("different", " "),
    ("government", " "),
    # ---- Common prefixes ----
    ("unhappy", " "),
    ("rediscover", " "),
    ("preview", " "),
    ("submarine", " "),
    ("antivirus", " "),
    ("bicycle", " "),
    ("triangle", " "),
    ("microscope", " "),
    ("kilometer", " "),
    ("megabyte", " "),
    # ---- Latin and borrowed ----
    ("et cetera", " "),
    ("ad hoc", " "),
    ("per se", " "),
    ("vice versa", " "),
    ("status quo", " "),
    ("alma mater", " "),
    ("bona fide", " "),
    ("carpe diem", " "),
    ("quid pro quo", " "),
    ("habeas corpus", " "),
    # ---- Very long context (stress trie) ----
    ("the quick brown fox jumps over the lazy do", "g"),
    ("In the beginning was the Word, and the Word was with Go", "d"),
    ("To be or not to be, that is the questio", "n"),
    ("It was the best of times, it was the worst of time", "s"),
    ("All happy families are alike; each unhappy family is unhapp", "y"),
    # ---- Abbreviations ----
    ("vs. ", " "),
    ("etc. ", " "),
    ("approx. ", " "),
    ("Prof. ", " "),
    ("Fig. ", " "),
    ("Vol. ", " "),
    ("No. ", " "),
    ("Rev. ", " "),
    ("Gen. ", " "),
    ("Sen. ", " "),
    # ---- Hyphen and compound ----
    ("well-known ", " "),
    ("state-of-the-art ", " "),
    ("twenty-one", " "),
    ("self-esteem", " "),
    ("mother-in-law", " "),
    ("long-term", " "),
    ("high-quality", " "),
    ("user-friendly", " "),
    ("part-time", " "),
    ("full-time", " "),
    # ---- Colons and semicolons ----
    ("Note: ", " "),
    ("Warning: ", " "),
    ("Example: ", " "),
    ("However; ", " "),
    ("Therefore; ", " "),
    ("First: ", " "),
    ("Step 1: ", " "),
    ("URL: ", " "),
    ("Date: ", " "),
    ("To: ", " "),
    # ---- Interjections ----
    ("Oh! ", " "),
    ("Ah! ", " "),
    ("Wow! ", " "),
    ("Ouch! ", " "),
    ("Hmm. ", " "),
    ("Uh. ", " "),
    ("Well, ", " "),
    ("So, ", " "),
    ("Like, ", " "),
    ("Anyway, ", " "),
    # ---- Double letters and spelling ----
    ("book", " "),
    ("letter", " "),
    ("happy", " "),
    ("balloon", " "),
    ("committee", " "),
    ("occurrence", " "),
    ("embarrass", " "),
    ("address", " "),
    ("success", " "),
    ("possess", " "),
    # ---- Palindromes and odd words ----
    ("racecar", " "),
    ("level", " "),
    ("radar", " "),
    ("kayak", " "),
    ("deified", " "),
    ("rotator", " "),
    ("repaper", " "),
    ("noon", " "),
    ("civic", " "),
    ("mom", " "),
    # ---- Onomatopoeia ----
    ("bang!", " "),
    ("boom!", " "),
    ("splash!", " "),
    ("meow", " "),
    ("woof", " "),
    ("buzz", " "),
    ("click", " "),
    ("pop", " "),
    ("zip", " "),
    ("crash", " "),
    # ---- Ordinals and list ----
    ("1st ", " "),
    ("2nd ", " "),
    ("3rd ", " "),
    ("4th ", " "),
    ("5th ", " "),
    ("first ", " "),
    ("second ", " "),
    ("third ", " "),
    ("Item 1.", " "),
    ("Step 2.", " "),
    # ---- Paths and URLs ----
    ("/home/user/", "d"),
    ("C:\\Users\\", "A"),
    ("http://example.", "c"),
    ("file:///tmp/", "x"),
    ("ftp://ftp.", "g"),
    ("www.example", "."),
    (".gitignore", " "),
    ("README.md", " "),
    ("src/main.", "p"),
    ("docs/api.", "h"),
    # ---- More edge ----
    ("word  ", " "),
    ("  space", " "),
    ("after newline", " "),
    ("tab\there", " "),
    ("mixedCase", " "),
    ("UPPERCASE", " "),
    ("lowercase", " "),
    ("CamelCase", " "),
    ("snake_case", " "),
    ("kebab-case", " "),
]


def get_input_lines():
    return [t[0] for t in UNIT_TEST_CASES]


def get_answer_lines():
    return [t[1] for t in UNIT_TEST_CASES]
