"""
Diverse unit test cases for the next-character predictor.
Each entry is (input_prefix, expected_next_character).
Designed to cover many unique scenarios; model is English-only so non-English and
symbol/code/edge cases should often fail, yielding ~10% or lower accuracy.
"""

# Format: list of (input_string, expected_next_char)
# Categories are commented for clarity; many unique ideas per category.

UNIT_TEST_CASES = [
    # ---- Non-English: Spanish ----
    ("Hola mund", "o"),
    ("¿Qué tal ", "e"),
    ("Buenos dí", "a"),
    ("Gracias por tu ayu", "d"),
    ("El gato está en la ventan", "a"),
    ("Me gusta la comid", "a"),
    ("Hasta luego, amig", "o"),
    ("¿Dónde está la bibliotec", "a"),
    ("No entiendo nad", "a"),
    ("Por favor, ayud", "a"),
    # ---- Non-English: Russian ----
    ("Привет ми", "р"),
    ("Спасибо больш", "о"),
    ("Как дела", "?"),
    ("Доброе утро", ","),
    ("До свидани", "я"),
    ("Меня зовут Алекса", "н"),
    ("Где здесь туалет", "?"),
    ("Это очень красив", "о"),
    ("Хорошего дн", "я"),
    ("Пожалуйста, помогите м", "н"),
    # ---- Non-English: Chinese ----
    ("你好世", "界"),
    ("谢谢你的帮", "助"),
    ("今天天气很好", "。"),
    ("我是学", "生"),
    ("再见，朋", "友"),
    ("请问厕所在哪", "里"),
    ("这个很好吃", "。"),
    ("明天见", "。"),
    ("对不起，我不懂", "。"),
    ("欢迎来到北", "京"),
    # ---- Non-English: Arabic ----
    ("مرحبا بك", " "),
    ("شكرا جزيلا", " "),
    ("كيف حالك", "؟"),
    ("مع السلامة", " "),
    ("أنا طالب", " "),
    ("أين الحمام", "؟"),
    ("هذا لذيذ", " "),
    ("إلى اللقاء", " "),
    ("من فضلك ساعدني", " "),
    ("أهلا وسهلا", " "),
    # ---- Punctuation and formatting ----
    ("Mr. ", "S"),
    ("Dr. ", " "),
    ("e.g. ", " "),
    ("i.e. ", " "),
    ("U.S. ", " "),
    ("Yes! ", " "),
    ("Wait... ", " "),
    ("Note: ", " "),
    ("Hello—world", " "),
    ("(parenthesis) ", " "),
    # ---- Contractions and apostrophes ----
    ("don't ", "w"),
    ("it's ", "a"),
    ("I'm ", "s"),
    ("we're ", "g"),
    ("they've ", "b"),
    ("can't ", " "),
    ("won't ", " "),
    ("John's ", "c"),
    ("that's ", "w"),
    ("what's ", "u"),
    # ---- Rare or long English words ----
    ("unbelievable", " "),
    ("questionnaire", " "),
    ("necessary", " "),
    ("accommodation", " "),
    # ---- Short / edge context ----
    ("", " "),
    ("a", " "),
    ("x", " "),
    ("q", "u"),
    ("z", " "),
    (" ", " "),
    ("\t", " "),
    (".", " "),
    ("?", " "),
    ("!", " "),
    # ---- Repetition and patterns ----
    ("aaaaaaa", "a"),
    ("aaaaaaa", " "),
    ("the the the ", "t"),
    ("abcabcab", "c"),
    ("1231231", "2"),
    # ---- Mixed language ----
    ("Hello 世界", " "),
    ("Adiós friends", " "),
    # ---- Slang and informal ----
    ("OMG that's ", "s"),
    ("LOL so funn", "y"),
    ("BRB in a sec", " "),
    ("IMO the best", " "),
    ("FYI we're late", " "),
    ("TBH I don't know", " "),
    ("IDK what to do", " "),
    ("ASAP please", " "),
    ("RSVP by Friday", " "),
    ("DIY project", " "),
    # ---- Dates and time ----
    ("Jan 1, 202", "4"),
    ("12:30 ", "p"),
    ("Q1 202", "4"),
    ("March 15, 200", "0"),
    ("Mon Dec 0", "1"),
    ("09:00 AM", " "),
    ("1st place", " "),
    ("2nd floor", " "),
    ("3rd time", " "),
    ("Chapter IV", " "),
    # ---- Quotes and brackets ----
    ("'Hello' ", "s"),
    ('"Yes" ', "s"),
    ("(example)", " "),
    ("[array]", " "),
    ("{key}: ", '"'),
    ("<tag", ">"),
    ("'Single quoted", "'"),
    ("\"Double quoted", '"'),
    ("Back `tick`", " "),
    ("—em dash—", " "),
    # ---- Emoji and Unicode ----
    ("Hello 😀", " "),
    ("Thumbs up 👍", " "),
    ("مرحبا", " "),
    ("Привет", " "),
    # ---- Sentence boundaries ----
    ("Hello. ", "I"),
    ("Really? ", " "),
    ("No! ", " "),
    ("Okay. ", "L"),
    ("Done. ", " "),
    ("Sure. ", " "),
    ("Maybe. ", " "),
    ("Thanks. ", " "),
    ("Sorry. ", " "),
    ("Wait. ", " "),
    # ---- Common suffixes ----
    ("running ", " "),
    ("happily ", " "),
    ("question", " "),
    ("happiness", " "),
    ("beautiful", " "),
    ("quickly", " "),
    ("national", " "),
    ("important", " "),
    ("different", " "),
    ("government", " "),
    # ---- Common prefixes ----
    ("unhappy", " "),
    ("rediscover", " "),
    ("preview", " "),
    ("submarine", " "),
    ("antivirus", " "),
    ("bicycle", " "),
    ("triangle", " "),
    ("microscope", " "),
    ("kilometer", " "),
    ("megabyte", " "),
    # ---- Latin and borrowed ----
    ("et cetera", " "),
    ("ad hoc", " "),
    ("per se", " "),
    ("vice versa", " "),
    ("status quo", " "),
    # ---- Very long context (stress trie) ----
    ("the quick brown fox jumps over the lazy do", "g"),
    ("In the beginning was the Word, and the Word was with Go", "d"),
    ("To be or not to be, that is the questio", "n"),
    ("It was the best of times, it was the worst of time", "s"),
    ("All happy families are alike; each unhappy family is unhapp", "y"),
    # ---- Abbreviations ----
    ("vs. ", " "),
    ("etc. ", " "),
    ("approx. ", " "),
    ("Prof. ", " "),
    ("Fig. ", " "),
    ("Vol. ", " "),
    ("No. ", " "),
    ("Rev. ", " "),
    ("Gen. ", " "),
    ("Sen. ", " "),
    # ---- Hyphen and compound ----
    ("well-known ", " "),
    ("state-of-the-art ", " "),
    ("twenty-one", " "),
    ("self-esteem", " "),
    ("mother-in-law", " "),
    ("long-term", " "),
    ("high-quality", " "),
    ("user-friendly", " "),
    ("part-time", " "),
    ("full-time", " "),
    # ---- Colons and semicolons ----
    ("Note: ", " "),
    ("Warning: ", " "),
    ("Example: ", " "),
    ("However; ", " "),
    ("Therefore; ", " "),
    ("First: ", " "),
    ("Step 1: ", " "),
    ("URL: ", " "),
    ("Date: ", " "),
    ("To: ", " "),
    # ---- Interjections ----
    ("Oh! ", " "),
    ("Ah! ", " "),
    ("Wow! ", " "),
    ("Ouch! ", " "),
    ("Hmm. ", " "),
    ("Uh. ", " "),
    ("Well, ", " "),
    ("So, ", " "),
    ("Like, ", " "),
    ("Anyway, ", " "),
    # ---- Double letters and spelling ----
    ("book", " "),
    ("letter", " "),
    ("happy", " "),
    ("balloon", " "),
    ("committee", " "),
    ("occurrence", " "),
    ("embarrass", " "),
    ("address", " "),
    ("success", " "),
    ("possess", " "),
    # ---- Onomatopoeia ----
    ("bang!", " "),
    ("boom!", " "),
    ("splash!", " "),
    ("meow", " "),
    ("woof", " "),
    ("buzz", " "),
    ("click", " "),
    ("pop", " "),
    ("zip", " "),
    ("crash", " "),
]


def get_input_lines():
    return [t[0] for t in UNIT_TEST_CASES]


def get_answer_lines():
    return [t[1] for t in UNIT_TEST_CASES]
